apiVersion: v1
kind: Service
metadata:
  name: stackbase-api-service
  namespace: stackbase
  labels:
    app: stackbase-api
spec:
  selector:
    app: stackbase-api
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
