apiVersion: v1
kind: Service
metadata:
  name: stackbase-web-service
  namespace: stackbase
  labels:
    app: stackbase-web
spec:
  selector:
    app: stackbase-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
